name: BTC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libdbus-1-dev

    - name: Install Django
      run: |
        pip install django

    - name: Clean requirements file
      run: |
        pip freeze > requirements.txt

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    # - name: Run migrations
    #   run: |
    #     python manage.py migrate

    - name: Run tests
      run: |
        python manage.py test
